version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mkdir test-reports
            pip install coverage
            coverage run --source "pyliturgical" setup.py test --addopts "--junitxml=test-reports/junit.xml"
            coverage report
            coverage xml -o test-reports/coverage.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: verify git tag vs. version
          command: |
            python setup.py verify
      - run:
          name: build source distribution
          command: |
            python setup.py sdist
      - run:
          name: build wheel
          command: |
            python setup.py bdist_wheel
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install twine
            twine upload dist/*
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
